// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "SuckWheel.h"
#include "../RobotMap.h"
#include "../Robot.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

SuckWheel::SuckWheel() : Subsystem("SuckWheel") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	wheel = RobotMap::suckWheelWheel;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void SuckWheel::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void SuckWheel::SpinIn()
{
while((Robot::oi->getJoystick1()->GetRawButton(1))&&!(Robot::oi->getJoystick1()->GetRawButton(2))&&!(Robot::oi->getJoystick1()->GetRawButton(3))){
	wheel->Set(0.5);
}
}

void SuckWheel::SpinOut()
{
while((Robot::oi->getJoystick1()->GetRawButton(2))&&!(Robot::oi->getJoystick1()->GetRawButton(1))&&!(Robot::oi->getJoystick1()->GetRawButton(3))){
	wheel->Set(-0.5);
}
}

void SuckWheel::SpinStop()
{
while((Robot::oi->getJoystick1()->GetRawButton(3))&&!(Robot::oi->getJoystick1()->GetRawButton(1))&&!(Robot::oi->getJoystick1()->GetRawButton(2))){
	wheel->Set(0);
}
}
// Put methods for controlling this subsystem
// here. Call these from Commands.

