// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Eject.h"
#include "Commands/SpinIn.h"
#include "Commands/SpinOut.h"
#include "Commands/SpinStop.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	joystick1 = new Joystick(0);
	
	joystickButton4 = new JoystickButton(joystick1, 8);
	joystickButton4->WhenPressed(new Eject());
	joystickButton3 = new JoystickButton(joystick1, 3);
	joystickButton3->WhenPressed(new SpinStop());
	joystickButton2 = new JoystickButton(joystick1, 2);
	joystickButton2->WhenPressed(new SpinOut());
	joystickButton1 = new JoystickButton(joystick1, 1);
	joystickButton1->WhenPressed(new SpinIn());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("SpinIn", new SpinIn());

	SmartDashboard::PutData("SpinOut", new SpinOut());

	SmartDashboard::PutData("SpinStop", new SpinStop());

	SmartDashboard::PutData("Eject", new Eject());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getJoystick1() {
	return joystick1;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
